language: java
jdk: openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d

before_script:
  - cd ../../src

addons:
  sonarcloud:
    organization: "jordanbgt-github"
    toekn: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -P test-consumer,test-business sonar:sonar -Dsonar.projectKey=JordanBgt_OPC_Projet9

after_success:
  - cd docker/dev
  - docker-compose stop
